=== ThinkingBeing/ccdebug/ccdemo/tools/json_template/myApplication/myapplication-dsl.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MyApplication Schema",
  "description": "MyApplication JSON 是对应用程序描述的JSON格式文件，主要包含应用程序的基本信息",
  "type": "object",
  "required": [
    "metadataType",
    "createdBy",
    "createdOn",
    "modifiedBy",
    "modifiedOn",
    "applicationGuid",
    "applicationName",
    "application",
    "shortName",
    "description"
  ],
  "properties": {
    "metadataType": {
      "type": "string",
      "description": "当前元数据类型",
      "enum": ["MyApplication"]
    },
    "createdBy": {
      "type": "string",
      "description": "创建人"
    },
    "createdOn": {
      "type": "string",
      "description": "创建时间，日期类型",
      "format": "date-time"
    },
    "modifiedBy": {
      "type": "string",
      "description": "修改人"
    },
    "modifiedOn": {
      "type": "string",
      "description": "修改时间",
      "format": "date-time"
    },
    "applicationGuid": {
      "type": "string",
      "description": "应用GUID，唯一标识",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "applicationName": {
      "type": "string",
      "description": "应用名称"
    },
    "application": {
      "type": "string",
      "description": "应用编码，取自 <MyApplication> 元数据的 application 属性",
      "pattern": "^(x_\\d+|\\d+)$"
    },
    "shortName": {
      "type": "string",
      "description": "应用简称"
    },
    "description": {
      "type": "string",
      "description": "应用描述信息"
    }
  }
}

=== ThinkingBeing/ccdebug/ccdemo/tools/json_template/myApplication/myapplication-dsl.template.json
{
  "metadataType": "MyApplication",
  "createdBy": "创建人",
  "createdOn": "2023-06-20T17:22:01.2935753+08:00",
  "modifiedBy": "修改人",
  "modifiedOn": "2023-06-20T19:21:00.6857054+08:00",
  "applicationGuid": "be41b639-8c95-4afd-980f-61a8411bb1d4",
  "applicationName": "AI-财务管理",
  "application": "x_3825",
  "shortName": "finan_wSdl",
  "description": "汇总集团以及集团下各子公司相应的报销、资金往来、个人借还款、工程付款等等表单流程数据，并且其中工程付款与工程预算以及工程采购之间也有相对应数据之间的联动业务，在实现财务数据统一的前提下，也很好的做到了各应用间的数据更新。"
}
