=== ThinkingBeing/ccdebug/ccdemo/tools/json_template/myfunction/myfunction-dsl.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MyFunction Schema",
  "description": "MyFunction JSON 是对业务单元描述的JSON格式文件，主要包含业务单元的基本信息、操作和主页配置",
  "type": "object",
  "required": [
    "metadataType",
    "createdBy",
    "createdOn",
    "modifiedBy",
    "modifiedOn",
    "metadataStatus",
    "functionGuid",
    "functionName",
    "hierarchyCode",
    "parentHierarchyCode",
    "level",
    "isDisabled",
    "functionCode",
    "application",
    "parentFunctionGuid",
    "iconClass",
    "iconColor",
    "orderId",
    "actions",
    "homePages"
  ],
  "properties": {
    "metadataType": {
      "type": "string",
      "description": "当前元数据类型",
      "enum": ["MyFunction"]
    },
    "createdBy": {
      "type": "string",
      "description": "创建人"
    },
    "createdOn": {
      "type": "string",
      "description": "创建时间，日期类型",
      "format": "date-time"
    },
    "modifiedBy": {
      "type": "string",
      "description": "修改人"
    },
    "modifiedOn": {
      "type": "string",
      "description": "修改时间，日期类型",
      "format": "date-time"
    },
    "metadataStatus": {
      "type": "string",
      "description": "状态，枚举类型",
      "enum": ["Product", "Customize"]
    },
    "functionGuid": {
      "type": "string",
      "description": "业务单元唯一ID，GUID类型",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "functionName": {
      "type": "string",
      "description": "业务单元名称"
    },
    "hierarchyCode": {
      "type": "string",
      "description": "层级编码"
    },
    "parentHierarchyCode": {
      "type": "string",
      "description": "父层级编码"
    },
    "level": {
      "type": "integer",
      "description": "层级级别"
    },
    "isDisabled": {
      "type": "boolean",
      "description": "是否禁用"
    },
    "functionCode": {
      "type": "string",
      "description": "业务单元编码"
    },
    "application": {
      "type": "string",
      "description": "应用（子系统）编码"
    },
    "parentFunctionGuid": {
      "type": ["string", "null"],
      "description": "父业务单元GUID",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "iconClass": {
      "type": "string",
      "description": "图标样式类"
    },
    "iconColor": {
      "type": "string",
      "description": "图标颜色"
    },
    "orderId": {
      "type": "string",
      "description": "排序ID"
    },
    "actions": {
      "type": ["array", "null"],
      "description": "业务单元操作列表",
      "items": {
        "$ref": "#/definitions/action"
      }
    },
    "homePages": {
      "type": ["array", "null"],
      "description": "主页配置列表",
      "items": {
        "$ref": "#/definitions/homePage"
      }
    }
  },
  "definitions": {
    "action": {
      "type": "object",
      "required": [
        "actionCode",
        "actionName",
        "comments",
        "createdOn",
        "modifiedOn",
        "actionType"
      ],
      "properties": {
        "actionCode": {
          "type": "string",
          "description": "操作编码"
        },
        "actionName": {
          "type": "string",
          "description": "操作名称"
        },
        "comments": {
          "type": "string",
          "description": "操作描述"
        },
        "createdOn": {
          "type": "string",
          "description": "创建时间",
          "format": "date-time"
        },
        "modifiedOn": {
          "type": "string",
          "description": "修改时间",
          "format": "date-time"
        },
        "actionType": {
          "type": "integer",
          "description": "操作类型"
        }
      }
    },
    "homePage": {
      "type": "object",
      "required": [
        "id",
        "pageName",
        "openMode",
        "pageId",
        "iconClass",
        "params"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "主页配置ID",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "pageName": {
          "type": "string",
          "description": "页面名称"
        },
        "openMode": {
          "type": "integer",
          "description": "打开方式",
          "enum": [0, 1]
        },
        "pageId": {
          "type": "string",
          "description": "页面ID",
          "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "iconClass": {
          "type": "string",
          "description": "图标样式类"
        },
        "params": {
          "type": "array",
          "description": "参数列表",
          "items": {
            "$ref": "#/definitions/param"
          }
        }
      }
    },
    "param": {
      "type": "object",
      "required": [
        "type",
        "key",
        "value"
      ],
      "properties": {
        "type": {
          "type": "string",
          "description": "参数类型",
          "enum": ["text"]
        },
        "key": {
          "type": "string",
          "description": "参数键"
        },
        "value": {
          "type": "string",
          "description": "参数值"
        }
      }
    }
  }
}

=== ThinkingBeing/ccdebug/ccdemo/tools/json_template/myfunction/myfunction-dsl.template.json
{
    "metadataType": "MyFunction",
    "createdBy": "创建人",
    "createdOn": "2025-09-22T10:25:33.4815536+08:00",
    "modifiedBy": "修改人",
    "modifiedOn": "2025-09-22T11:17:17.8521089+08:00",
    "metadataStatus": "Customize",
    "functionGuid": "08ddf97f-4ece-49b9-8560-a5c8c5ab22c1",
    "functionName": "车辆管理",
    "hierarchyCode": "x_001113.x_00111301",
    "parentHierarchyCode": "x_001113",
    "level": 1,
    "isDisabled": false,
    "functionCode": "x_00111301",
    "application": "0011",
    "parentFunctionGuid": "08ddf97f-15fa-49b8-8f7d-4a36d361dfb5",
    "iconClass": "mp-icon-application",
    "iconColor": "#4598F0",
    "orderId": "25949",
    "actions": [
        {
            "actionCode": "x_00",
            "actionName": "查询",
            "comments": "查询",
            "createdOn": "0001-01-01T00:00:00.000Z",
            "modifiedOn": "0001-01-01T00:00:00.000Z",
            "actionType": 1
        },
        {
            "actionCode": "x_01",
            "actionName": "新建",
            "comments": "新建",
            "createdOn": "0001-01-01T00:00:00.000Z",
            "modifiedOn": "0001-01-01T00:00:00.000Z",
            "actionType": 3
        },
        {
            "actionCode": "x_02",
            "actionName": "修改",
            "comments": "修改",
            "createdOn": "0001-01-01T00:00:00.000Z",
            "modifiedOn": "0001-01-01T00:00:00.000Z",
            "actionType": 4
        },
        {
            "actionCode": "x_03",
            "actionName": "删除",
            "comments": "删除",
            "createdOn": "0001-01-01T00:00:00.000Z",
            "modifiedOn": "0001-01-01T00:00:00.000Z",
            "actionType": 3
        }
    ],
    "homePages": [
        {
            "id": "08ddf97f-4ece-4b3c-8e84-fcfae7c2a5dc",
            "pageName": "车辆管理",
            "openMode": 0,
            "pageId": "3159bf02-430e-e811-8b8c-94c69104026b",
            "iconClass": "mp-icon-chart-proportion",
            "params": [
                {
                    "type": "text",
                    "key": "openMode",
                    "value": "add"
                },
                {
                    "type": "text",
                    "key": "from",
                    "value": "wx"
                }
            ]
        }
    ]
}
